// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-BR3L60F
// DateTime: 09.10.2022 1:45:30
// UserName: Mike
// Input file <SimpleYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using ProgramTree;

namespace SimpleParser
{
public enum Tokens {
    error=1,EOF=2,BEGIN=3,END=4,CYCLE=5,ASSIGN=6,
    SEMICOLON=7,WHILE=8,DO=9,REPEAT=10,UNTIL=11,FOR=12,
    TO=13,WRITE=14,LPAR=15,RPAR=16,IF=17,THEN=18,
    ELSE=19,VAR=20,COMMA=21,PLUS=22,MINUS=23,MUL=24,
    DIV=25,INUM=26,RNUM=27,ID=28};

public struct ValueType
{ 
			public double dVal; 
			public int iVal; 
			public string sVal; 
			public Node nVal;
			public ExprNode eVal;
			public StatementNode stVal;
			public BlockNode blVal;
       }
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SimpleYacc.y
// Эти объявления добавляются в класс GPPGParser, представляющий собой парсер, генерируемый системой gppg
    public BlockNode root; // Корневой узел синтаксического дерева 
    public Parser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[35];
  private static State[] states = new State[71];
  private static string[] nonTerms = new string[] {
      "expr", "ident", "expr2", "expr3", "assign", "statement", "cycle", "while", 
      "repeat", "for", "write", "if", "var", "stlist", "block", "progr", "$accept", 
      };

  static Parser() {
    states[0] = new State(new int[]{3,4},new int[]{-16,1,-15,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-14,5,-6,70,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[5] = new State(new int[]{4,6,7,7});
    states[6] = new State(-25);
    states[7] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,8,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[8] = new State(-4);
    states[9] = new State(-5);
    states[10] = new State(new int[]{6,11});
    states[11] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,12,-3,28,-4,27,-2,17});
    states[12] = new State(new int[]{22,13,23,23,4,-15,7,-15,11,-15,19,-15});
    states[13] = new State(new int[]{28,18,26,19,15,20},new int[]{-3,14,-4,27,-2,17});
    states[14] = new State(new int[]{24,15,25,25,22,-17,23,-17,4,-17,7,-17,11,-17,19,-17,16,-17,28,-17,3,-17,5,-17,8,-17,10,-17,12,-17,14,-17,17,-17,20,-17,9,-17,13,-17,18,-17});
    states[15] = new State(new int[]{28,18,26,19,15,20},new int[]{-4,16,-2,17});
    states[16] = new State(-20);
    states[17] = new State(-22);
    states[18] = new State(-14);
    states[19] = new State(-23);
    states[20] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,21,-3,28,-4,27,-2,17});
    states[21] = new State(new int[]{16,22,22,13,23,23});
    states[22] = new State(-24);
    states[23] = new State(new int[]{28,18,26,19,15,20},new int[]{-3,24,-4,27,-2,17});
    states[24] = new State(new int[]{24,15,25,25,22,-18,23,-18,4,-18,7,-18,11,-18,19,-18,16,-18,28,-18,3,-18,5,-18,8,-18,10,-18,12,-18,14,-18,17,-18,20,-18,9,-18,13,-18,18,-18});
    states[25] = new State(new int[]{28,18,26,19,15,20},new int[]{-4,26,-2,17});
    states[26] = new State(-21);
    states[27] = new State(-19);
    states[28] = new State(new int[]{24,15,25,25,22,-16,23,-16,4,-16,7,-16,11,-16,19,-16,16,-16,28,-16,3,-16,5,-16,8,-16,10,-16,12,-16,14,-16,17,-16,20,-16,9,-16,13,-16,18,-16});
    states[29] = new State(-6);
    states[30] = new State(-7);
    states[31] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,32,-3,28,-4,27,-2,17});
    states[32] = new State(new int[]{22,13,23,23,28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,33,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[33] = new State(-26);
    states[34] = new State(-8);
    states[35] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,36,-3,28,-4,27,-2,17});
    states[36] = new State(new int[]{9,37,22,13,23,23});
    states[37] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,38,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[38] = new State(-27);
    states[39] = new State(-9);
    states[40] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,41,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[41] = new State(new int[]{11,42});
    states[42] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,43,-3,28,-4,27,-2,17});
    states[43] = new State(new int[]{22,13,23,23,4,-28,7,-28,11,-28,19,-28});
    states[44] = new State(-10);
    states[45] = new State(new int[]{28,18},new int[]{-2,46});
    states[46] = new State(new int[]{6,47});
    states[47] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,48,-3,28,-4,27,-2,17});
    states[48] = new State(new int[]{13,49,22,13,23,23});
    states[49] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,50,-3,28,-4,27,-2,17});
    states[50] = new State(new int[]{9,51,22,13,23,23});
    states[51] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,52,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[52] = new State(-29);
    states[53] = new State(-11);
    states[54] = new State(new int[]{15,55});
    states[55] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,56,-3,28,-4,27,-2,17});
    states[56] = new State(new int[]{16,57,22,13,23,23});
    states[57] = new State(-30);
    states[58] = new State(new int[]{19,59,4,-12,7,-12,11,-12});
    states[59] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,60,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[60] = new State(-32);
    states[61] = new State(new int[]{28,18,26,19,15,20},new int[]{-1,62,-3,28,-4,27,-2,17});
    states[62] = new State(new int[]{18,63,22,13,23,23});
    states[63] = new State(new int[]{28,18,3,4,5,31,8,35,10,40,12,45,14,54,17,61,20,68},new int[]{-6,64,-5,9,-2,10,-15,29,-7,30,-8,34,-9,39,-10,44,-11,53,-12,58,-13,65});
    states[64] = new State(-31);
    states[65] = new State(new int[]{21,66,4,-13,7,-13,11,-13,19,-13});
    states[66] = new State(new int[]{28,18},new int[]{-2,67});
    states[67] = new State(-34);
    states[68] = new State(new int[]{28,18},new int[]{-2,69});
    states[69] = new State(-33);
    states[70] = new State(-3);

    rules[1] = new Rule(-17, new int[]{-16,2});
    rules[2] = new Rule(-16, new int[]{-15});
    rules[3] = new Rule(-14, new int[]{-6});
    rules[4] = new Rule(-14, new int[]{-14,7,-6});
    rules[5] = new Rule(-6, new int[]{-5});
    rules[6] = new Rule(-6, new int[]{-15});
    rules[7] = new Rule(-6, new int[]{-7});
    rules[8] = new Rule(-6, new int[]{-8});
    rules[9] = new Rule(-6, new int[]{-9});
    rules[10] = new Rule(-6, new int[]{-10});
    rules[11] = new Rule(-6, new int[]{-11});
    rules[12] = new Rule(-6, new int[]{-12});
    rules[13] = new Rule(-6, new int[]{-13});
    rules[14] = new Rule(-2, new int[]{28});
    rules[15] = new Rule(-5, new int[]{-2,6,-1});
    rules[16] = new Rule(-1, new int[]{-3});
    rules[17] = new Rule(-1, new int[]{-1,22,-3});
    rules[18] = new Rule(-1, new int[]{-1,23,-3});
    rules[19] = new Rule(-3, new int[]{-4});
    rules[20] = new Rule(-3, new int[]{-3,24,-4});
    rules[21] = new Rule(-3, new int[]{-3,25,-4});
    rules[22] = new Rule(-4, new int[]{-2});
    rules[23] = new Rule(-4, new int[]{26});
    rules[24] = new Rule(-4, new int[]{15,-1,16});
    rules[25] = new Rule(-15, new int[]{3,-14,4});
    rules[26] = new Rule(-7, new int[]{5,-1,-6});
    rules[27] = new Rule(-8, new int[]{8,-1,9,-6});
    rules[28] = new Rule(-9, new int[]{10,-6,11,-1});
    rules[29] = new Rule(-10, new int[]{12,-2,6,-1,13,-1,9,-6});
    rules[30] = new Rule(-11, new int[]{14,15,-1,16});
    rules[31] = new Rule(-12, new int[]{17,-1,18,-6});
    rules[32] = new Rule(-12, new int[]{-12,19,-6});
    rules[33] = new Rule(-13, new int[]{20,-2});
    rules[34] = new Rule(-13, new int[]{-13,21,-2});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // progr -> block
{ root = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 3: // stlist -> statement
{ 
				CurrentSemanticValue.blVal = new BlockNode(ValueStack[ValueStack.Depth-1].stVal); 
			}
        break;
      case 4: // stlist -> stlist, SEMICOLON, statement
{ 
				ValueStack[ValueStack.Depth-3].blVal.Add(ValueStack[ValueStack.Depth-1].stVal); 
				CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-3].blVal; 
			}
        break;
      case 5: // statement -> assign
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 6: // statement -> block
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 7: // statement -> cycle
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 8: // statement -> while
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 9: // statement -> repeat
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 10: // statement -> for
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 11: // statement -> write
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 12: // statement -> if
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 13: // statement -> var
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 14: // ident -> ID
{ CurrentSemanticValue.eVal = new IdNode(ValueStack[ValueStack.Depth-1].sVal); }
        break;
      case 15: // assign -> ident, ASSIGN, expr
{ CurrentSemanticValue.stVal = new AssignNode(ValueStack[ValueStack.Depth-3].eVal as IdNode, ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 16: // expr -> expr2
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 17: // expr -> expr, PLUS, expr2
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, '+'); }
        break;
      case 18: // expr -> expr, MINUS, expr2
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, '-'); }
        break;
      case 19: // expr2 -> expr3
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 20: // expr2 -> expr2, MUL, expr3
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, '*'); }
        break;
      case 21: // expr2 -> expr2, DIV, expr3
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, '/'); }
        break;
      case 22: // expr3 -> ident
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 23: // expr3 -> INUM
{ CurrentSemanticValue.eVal = new IntNumNode(ValueStack[ValueStack.Depth-1].iVal); }
        break;
      case 24: // expr3 -> LPAR, expr, RPAR
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-2].eVal; }
        break;
      case 25: // block -> BEGIN, stlist, END
{ CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal; }
        break;
      case 26: // cycle -> CYCLE, expr, statement
{ CurrentSemanticValue.stVal = new CycleNode(ValueStack[ValueStack.Depth-2].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 27: // while -> WHILE, expr, DO, statement
{ CurrentSemanticValue.stVal = new WhileNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 28: // repeat -> REPEAT, statement, UNTIL, expr
{ CurrentSemanticValue.stVal = new RepeatNode(ValueStack[ValueStack.Depth-3].stVal, ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 29: // for -> FOR, ident, ASSIGN, expr, TO, expr, DO, statement
{ CurrentSemanticValue.stVal = new ForNode(ValueStack[ValueStack.Depth-7].eVal as IdNode, ValueStack[ValueStack.Depth-5].eVal, ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 30: // write -> WRITE, LPAR, expr, RPAR
{ CurrentSemanticValue.stVal = new WriteNode(ValueStack[ValueStack.Depth-2].eVal); }
        break;
      case 31: // if -> IF, expr, THEN, statement
{ CurrentSemanticValue.stVal = new IfNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 32: // if -> if, ELSE, statement
{ 
		    (ValueStack[ValueStack.Depth-3].stVal as IfNode).Stat2 = ValueStack[ValueStack.Depth-1].stVal;
		    CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-3].stVal; 
		}
        break;
      case 33: // var -> VAR, ident
{ CurrentSemanticValue.stVal = new VarDefNode(ValueStack[ValueStack.Depth-1].eVal as IdNode); }
        break;
      case 34: // var -> var, COMMA, ident
{ 
		    (ValueStack[ValueStack.Depth-3].stVal as VarDefNode).Add(ValueStack[ValueStack.Depth-1].eVal as IdNode);
			CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-3].stVal;
		}
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
